version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=receipts
      - ETH_RPC_URL=http://anvil:8545
      - CONTRACT_ADDRESS=0x0 # Will be set after contract deployment
      - VERIFY_URL=http://localhost:8080/verify
    depends_on:
      - mongo
      - anvil

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    command: anvil --host 0.0.0.0

volumes:
  mongodb_data:
