version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: --mnemonic "test test test test test test test test test test test junk" --networkId 5777 --chainId 1337

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=receipts
      - ETH_RPC_URL=http://ganache:8545
      - CONTRACT_ADDRESS=0x0
      - VERIFY_URL=http://localhost:8080/verify
      - LISTEN_ADDR=:8080
    depends_on:
      - mongodb
      - ganache

volumes:
  mongodb_data: